# Copyright 2025 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: MIT

package = 't-doc-common'
version = 'stable'
hermetic = true

[tags]
testing = '0.64'
stable = '0.64'
previous = '0.63'

[defaults]
command = ['tdoc', 'serve', '--open']
command-dev = ['tdoc', 'serve', '--debug', '--watch=../common/tdoc',
               '--full-builds']
